#example1 = "https://www.youtube.com/playlist?list=PLHtyfDv32xnEVdkhAVsA5zHV34sFyjcOv"
#rap = "https://www.youtube.com/playlist?list=PLHtyfDv32xnG0E3_NzqO5wVvgkw7JcA_h"
#usao = "https://www.youtube.com/playlist?list=PLHtyfDv32xnH5lUzIB-9ofb54NLqUqhMF"