"https://www.youtube.com/playlist?list=PLHtyfDv32xnEVdkhAVsA5sFyjcOv" = "audio"
"https://www.youtube.com/playlist?list=PLHtyfDv32xnG0E3_NzqO5w7JcA_h" = "video"
"https://www.youtube.com/playlist?list=PL0usNGW1865yE7D83hLohy0gakwx" = "audio"